title: GeoDa
description: "GeoDa (TM): Software providing an introduction to spatial data analysis."
google_analytics: UA-72724100-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
